services:

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 10

  eureka-server:
    build: ./eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "6767:6767"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server

  productos:
    build: ./productos
    container_name: productos
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-pedidos:
    build: ./ms-pedidos
    container_name: ms-pedidos
    ports:
      - "8083:8083"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-inventario:
    build: ./ms-inventario
    container_name: ms-inventario
    ports:
      - "8084:8084"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-checkout:
    build: ./ms-checkout-fix
    container_name: ms-checkout
    ports:
      - "8085:8085"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql
      - productos
      - ms-inventario
      - ms-pedidos

  ms-report:
    build: ./ms-report
    container_name: ms-report
    ports:
      - "8086:8086"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-review:
    build: ./ms-review
    container_name: ms-review
    ports:
      - "8087:8087"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-notification:
    build: ./ms-notification
    container_name: ms-notification
    ports:
      - "8088:8088"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-delivery:
    build: ./ms-delivery
    container_name: ms-delivery
    ports:
      - "8089:8089"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-computer:
    build: ./ms-computer
    container_name: ms-computer
    ports:
      - "8090:8090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

  ms-user-fixed:
    build: ./ms-user-fixed
    container_name: ms-user-fixed
    ports:
      - "9090:9090"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - eureka-server
      - mysql

volumes:
  mysql-data:
