spring.application.name=ms-checkout

# Puerto
server.port=8085

# JWT (misma clave que los otros microservicios)
jwt.secret=una_clave_secreta_larga_y_segura_de_al_menos_32_bytes
eureka.instance.prefer-ip-address=true

# URLs de los otros microservicios
productos.service.url=http://localhost:8082
inventario.service.url=http://localhost:8084
pedidos.service.url=http://localhost:8083
